### ISSUE TITLE
Add one NeurIPS 2023 paper to CLIP-driven Application/Dense Prediction section

### ISSUE THREAD

**Issue by franciszzj** [zhaozh10/Awesome-CLIP-in-Medical-Imaging#2]
Thank you very much for your detailed survey of the work on CLIP in Medical Imaging. We recognize the complexity of this work and are very grateful for your efforts.
We would also like to recommend our paper accepted by NeurIPS 2023, Text Promptable Surgical Instrument Segmentation with Vision-Language Models (paper: https://arxiv.org/abs/2306.09244, code: https://github.com/franciszzj/TP-SIS). This paper utilizes a CLIP model to construct a text-promptable surgical instrument segmentation model. We believe this fits well with the **CLIP-driven Application/Dense Prediction** section of the review.
Thank you in advance for considering our suggestion.

**Comment by zhaozh10** [comment]
Thanks for your contribution to this field. We've updated this paper. We eagerly anticipate your further work.

**Comment by franciszzj** [comment]
Many thanks!
